language: node_js

node_js:
  - 8.12

services:
  - postgresql


before_script:
  cd movie_rank;
  createdb -U postgres MovieRank_Test;
  psql MovieRank_Test < test/db.sql;

install:
  cd movie_rank;
  npm install;
 
cache:
  directories:
    - "node_modules"




