language: node_js

node_js:
  - 8.12

services:
  - postgresql

<<<<<<< HEAD
before_install:
  npm i -g npm@6.4.1;
  npm i -g mocha;
  npm i chai;
=======
>>>>>>> f7cc2ea3910b0e68ed6fb4ac25a6560cb3a11928

before_script:
  cd movie_rank;
  createdb -U postgres MovieRank_Test;
  psql MovieRank_Test < test/db.sql;

install:
  cd movie_rank;
  npm install;
 
cache:
  directories:
    - "node_modules"




