language: node_js

node_js:
  - 8.12

services:
  - postgresql

before_install:
  npm i -g npm@6.4.1;
  npm i mocha;
  npm i chai;

before_script:
  cd movie_rank;
  createdb -U postgres MovieRank_Test;
  psql MovieRank_Test < test/db.sql;


