-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 17:54:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MoveRank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MoveRank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MoveRank` DEFAULT CHARACTER SET utf8 ;
USE `MoveRank` ;

-- -----------------------------------------------------
-- Table `MoveRank`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`Actor` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dob` DATETIME NOT NULL,
  `thumbnail_url` VARCHAR(255) NULL,
  PRIMARY KEY (`aid`),
  UNIQUE INDEX `aid_UNIQUE` (`aid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoveRank`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`Movie` (
  `mid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `release_date` VARCHAR(45) NULL,
  `mpaa_rating` VARCHAR(45) NULL,
  `runtime` TIME(6) NULL,
  `description` VARCHAR(45) NULL,
  `thumbnail_url` VARCHAR(45) NULL,
  `gid` INT NOT NULL,
  `did` INT NOT NULL,
  PRIMARY KEY (`mid`),
  UNIQUE INDEX `mid_UNIQUE` (`mid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoveRank`.`MovieActor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`MovieActor` (
  `aid` INT NOT NULL,
  `mid` INT NOT NULL,
  PRIMARY KEY (`aid`, `mid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoveRank`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`Genre` (
  `gid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gid`),
  UNIQUE INDEX `gid_UNIQUE` (`gid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoveRank`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`Rating` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `uid` INT NOT NULL,
  PRIMARY KEY (`rid`),
  UNIQUE INDEX `rid_UNIQUE` (`rid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoveRank`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`Director` (
  `did` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`did`),
  UNIQUE INDEX `did_UNIQUE` (`did` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoveRank`.`MovieRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`MovieRating` (
  `mid` INT NOT NULL,
  `rid` INT NOT NULL,
  PRIMARY KEY (`mid`, `rid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoveRank`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoveRank`.`User` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `thumbnail_url` VARCHAR(45) NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC))
ENGINE = InnoDB;

USE `MoveRank`;

DELIMITER $$
USE `MoveRank`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MoveRank`.`Actor_AFTER_UPDATE` AFTER UPDATE ON `Actor` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
